### ISSUE TITLE
Lisp error : (void-variable ess-mode-map)

### ISSUE THREAD

**Issue by slackline** [mattfidler/ess-smart-underscore.el#5]
Updated to ess-20190102.1423 and on starting have encountered this error...

    Debugger entered--Lisp error: (void-variable ess-mode-map)                                                                                                                                                       
    (define-key ess-mode-map (kbd "_") (quote ess-smarter-underscore))                                                                                                                                             
    eval-buffer(#<buffer  *load*-323538> nil "/home/user/.emacs.d/lisp/ess-smart-underscore.el" nil t)  ; Reading at buffer position 12942                                                                          4  load-with-code-conversion("/home/user/.emacs.d/lisp/ess-smart-underscore.el" "/home/user/.emacs.d/lisp/ess-smart-underscore.el" nil t)                                                                          5  require(ess-smart-underscore)                                                                                                                                                                                  
    eval-buffer(#<buffer  *load*-812240> nil "/home/user/.emacs.d/settings/ess-settings.el" nil t)  ; Reading at buffer position 1340                                                                              
    load-with-code-conversion("/home/user/.emacs.d/settings/ess-settings.el" "/home/user/.emacs.d/settings/ess-settings.el" nil nil)                                                                               
    load("~/.emacs.d/settings/ess-settings.el")                                                                                                                                                                    
    eval-buffer(#<buffer  *load*> nil "/home/user/.emacs.d/init.el" nil t)  ; Reading at buffer position 2970                                                                                                      
    load-with-code-conversion("/home/user/.emacs.d/init.el" "/home/user/.emacs.d/init.el" t t)                                                                                                                     
    load("/home/user/.emacs.d/init" t t)                                                                                                                                                                           
    #[0 "^H\205\266^@     \306=\203^Q^@\307^H\310Q\202?^@ \311=\204^^^@\307^H\312Q\202?^@\313\307\314\315#\203*^@\316\202?^@\313\307\314\317#\203>^@\320\321\322!D\nB^R\323\202?^@\316\324^S\325^A\324\211#\210^K\$
    command-line()                                                                                                                                                                                                 
    normal-top-level()

Using ess-smartunderscore-20181112.2102 

If there is any additional information I can provide please let me know.

**Comment by mattfidler** [comment]
I removed ess-mode-map.  I'm unsure how long it will take to populate in melpa.

**Comment by slackline** [comment]
Great, thanks @mattfidler, seems to work fine with ess-20190111.1629.

**Comment by mattfidler** [comment]
Now the `_` doesn't work  at all;  Debating putting in this underscore fix or just leaving it alone.
