### ISSUE TITLE
use ess-cycle-assign instead of ess-S-assign?

### ISSUE THREAD

**Issue by idiot-z** [mattfidler/ess-smart-underscore.el#6]
Hi,
it seems like ess-smart-underscore doesn't work in superior R mode anymore.
It looks like ess-S-assign is deprecated and should be replaced by ess-cycle-assign.
Do you think of doing the replacement any time soon?
Thanks.

**Comment by mattfidler** [comment]
I just updated it.  I also added checking completions first before inserting an underscore.  if `a_` has completions in your r session <kbd>a</kbd> and then <kbd>_</kbd> will now insert `a_`

**Comment by idiot-z** [comment]
Alright thank you very much!
One last thing though: should it work in r-mode too? Because it only works in iESS for me.
